---
- hosts: leaf01
  user: cumulus
  become: yes
  gather_facts: no
  tasks:
    - name: api
      shell: ln -s /etc/nginx/sites-{available,enabled}/nvue.conf
    - name: api prepare
      shell: sed -i 's/listen localhost:8765 ssl;/listen \[::\]:8765 ipv6only=off ssl;/g' /etc/nginx/sites-available/nvue.conf
    - name: nginx restart
      shell: systemctl restart nginx
    - name: test
      shell: curl  -u 'cumulus:Academy123' --insecure https://127.0.0.1:8765/cue_v1/interface
      register: xxx
    - name: debug
      debug: msg={{ xxx.stdout }} 
    - name: test mh
      shell: curl -u 'cumulus:Academy123' --insecure -X 'GET' 'https://127.0.0.1:8765/nvue_v1/evpn/multihoming?rev=operational'
      # -u 'root:root' --insecure https://localhost:8765/dns_v1/native/nameserver
      #       shell: curl -u 'cumulus:Academy123' --insecure -X 'GET' 'https://127.0.0.1:8765/nvue_v1/evpn/multihoming?rev=operational' -H 'accept: application/json'
      register: xxx
    - name: debug
      debug: msg={{ xxx.stdout }} 
#{
#  "bond1": {
#    "bond": {
#      "down-delay": 0,
#      "lacp-rate": "fast",
#      "member": {
#        "swp1": {}
#      },
#      "up-delay": 0
#    },
#    "bridge": {
#      "domain": {
#        "br_default": {
#          "learning": "on"
#        }
#      }
#    },
#    "ip": {
#      "address": {}
#    },
#    "link": {
#      "mtu": 9216,
#      "state": {
#        "up": {}
#      },
